#!/usr/bin/env bash
# Regenerates the generated half of THIRD_PARTY_NOTICES: the license and NOTICE text of every module
# linked into bin/shunt and, in a second section, into bin/shunt-control (which carries the etcd
# tree the proxy must not, ADR-0015), from `go-licenses report`. The first half, code copied into
# this repository (CLAUDE.md lift procedure), is maintained by hand above the marker and kept as is.
# Test-tree programs (test/s3diff, test/bench) are not shipped and not listed.
#
#   GO_LICENSES=<go-licenses binary> scripts/third-party-notices.sh     (make licenses sets it)
set -euo pipefail
: "${GO_LICENSES:?set GO_LICENSES to a go-licenses binary; make licenses does}"
GO=${GO:-go}
out=THIRD_PARTY_NOTICES
marker='==================== MODULES LINKED INTO bin/shunt: generated by make licenses, do not edit below ===================='
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

awk -v m="$marker" '$0 == m { exit } { print }' "$out" > "$tmp/head"

# report <pkg> <csv-out> <files-out>: every module the package links, and the LICENSE/NOTICE files.
report() {
  "$GO_LICENSES" report "$1" 2> "$tmp/report.err" | sort > "$2" || { cat "$tmp/report.err" >&2; exit 1; }
  : > "$3"
  while IFS=, read -r pkg _ license; do
    case "$pkg" in github.com/blakegolliher/shunt*) continue ;; esac
    # go-licenses names a package or, when a module has no package at its root, the module.
    dir=$("$GO" list -f '{{.Dir}}' "$pkg" 2>/dev/null || "$GO" list -m -f '{{.Dir}}' "$pkg")
    while [ -n "$dir" ] && [ "$dir" != / ]; do
      lic=$(find "$dir" -maxdepth 1 -type f \( -name 'LICENSE*' -o -name 'COPYING*' \) | sort | head -n 1)
      if [ -n "$lic" ]; then
        printf '%s\t%s\t%s\n' "$pkg" "$license" "$lic" >> "$3"
        find "$dir" -maxdepth 1 -type f -name 'NOTICE*' | sort | while read -r n; do printf '%s\t%s\t%s\n' "$pkg" NOTICE "$n" >> "$3"; done
        break
      fi
      dir=$(dirname "$dir")
    done
  done < "$2"
}

# section <binary> <csv> <files>: one generated section.
section() {
  echo
  echo "Every module linked into $1, with its license, from go-licenses report:"
  echo
  sed 's/^/  /' "$2"
  sort -u -t$'\t' -k3,3 "$3" | sort -t$'\t' -k1,1 -k2,2 | while IFS=$'\t' read -r pkg kind file; do
    echo
    echo "--------------------------------------------------------------------------------"
    echo "$pkg ($kind): ${file#"$("$GO" env GOMODCACHE)/"}"
    echo "--------------------------------------------------------------------------------"
    cat "$file"
  done
}

report ./cmd/shunt "$tmp/shunt.csv" "$tmp/shunt.files"
report ./cmd/shunt-control "$tmp/control.csv" "$tmp/control.files"
if grep -q 'go.etcd.io' "$tmp/shunt.csv"; then echo "bin/shunt links etcd; the proxy must not (ADR-0015)" >&2; exit 1; fi

{
  sed -e :a -e '/^\n*$/{$d;N;ba' -e '}' "$tmp/head"
  echo
  echo "$marker"
  section bin/shunt "$tmp/shunt.csv" "$tmp/shunt.files"
  echo
  echo "==================== MODULES LINKED INTO bin/shunt-control (the control plane; etcd and its tree live here only, ADR-0015) ===================="
  section bin/shunt-control "$tmp/control.csv" "$tmp/control.files"
} > "$tmp/new"
mv "$tmp/new" "$out"
echo "THIRD_PARTY_NOTICES: bin/shunt $(grep -c . "$tmp/shunt.csv") packages, bin/shunt-control $(grep -c . "$tmp/control.csv") packages"
